name: Deploy Custom Functionality Plugin

on:
  push:
    tags:
      - 'v*.*.*' # Trigger für jede neue Version

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up SSH
      run: ./scripts/setup_ssh.sh

    - name: Deploy Plugin
      run: ./scripts/deploy.sh
